name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore /p:Version=1.0.${{github.run_number}};AssemblyVersion=1.0.${{github.run_number}};FileVersion=1.0.${{github.run_number}};PackageVersion=1.0.${{github.run_number}}
      - name: Test
        run: dotnet test -c Release --no-restore --verbosity normal
        env:
          LIR_RESOURCES_API_KEY: ${{ secrets.LIR_RESOURCES_API_KEY }}
      - name: Publish Nuget
        run: dotnet nuget push src/ClientsRipe/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

